name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
      - name: Print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
  build:
    runs-on: ubuntu-latest
    name: Build
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - name: Checkout tool
        uses: actions/checkout@v3
        with:
          repository: Illidanz/ProLogueTranslation
          token: ${{ secrets.GH_PAT }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Checkout data
        uses: actions/checkout@v3
        with:
          path: ProLogueData
      - name: Download data
        uses: suisei-cn/actions-download-file@v1.3.0
        with:
          url: ${{ secrets.URL_DATA }}
      - name: Extract data
        run: 7z x dn3.7z
      - name: Install dependencies
        run: pipenv --python 3.11 sync
      - name: Install ImageMagick
        run: |
          sudo apt install libfontconfig libharfbuzz-dev fuse libfuse2
          wget https://download.imagemagick.org/ImageMagick/download/binaries/magick
          chmod +x magick
      - name: Extract
        run: pipenv run python tool.py extract --rom
      - name: Repack
        run: pipenv run python tool.py repack
      - name: Upload patch
        uses: actions/upload-artifact@v3
        with:
          name: patch.xdelta
          path: ProLogueData/patch.xdelta
          retention-days: 7
      - name: Check patch existence
        id: check_patch
        uses: andstor/file-existence-action@v2
        with:
          files: "ProLogueData/patch.xdelta"
      - name: Webhook
        if: ${{ steps.check_patch.outputs.files_exists == 'true' }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "A new nightly patch is available for testing! ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          username: "AGTTBot"
          avatar-url: "https://avatars.githubusercontent.com/u/123242276?v=4"
          filename: "ProLogueData/patch.xdelta"
