name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Checkout tool
        uses: actions/checkout@v3
        with:
          repository: Illidanz/ProLogueTranslation
          token: ${{ secrets.GH_PAT }}
      - name: Checkout data
        uses: actions/checkout@v3
        with:
          path: ProLogueData
      - name: Download data
        uses: suisei-cn/actions-download-file@v1.3.0
        with:
          url: ${{ secrets.URL_DATA }}
          target: ProLogueData
      - name: Extract data
        run: |
          cd ProLogueData
          7z x dn3.7z
      - name: Download tools
        uses: suisei-cn/actions-download-file@v1.3.0
        with:
          url: ${{ secrets.URL_TOOLS }}
      - name: Extract tools
        run: 7z x tools.7z
      - name: Install dependencies
        run: pipenv --python 3.10 sync
      - name: Extract
        run: pipenv run python tool.py extract
      - name: Repack
        run: pipenv run python tool.py --log repack
      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: tool.log
          path: tool.log
      - name: Upload patch
        uses: actions/upload-artifact@v3
        with:
          name: patch.xdelta
          path: ProLogueData/patch.xdelta
